version: "3"
services:
  db:
    image: postgres
    container_name: trasnTest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"